# conf/app.conf.example
appname = shadowing
httpport = 8086
runmode = dev

sessionon = true

[dev]
db_host=localhost
db_name=shadowing
db_port=5432
db_user=admin
db_pass=admin
[prod]
db_host=localhost
db_name=shadowing
db_port=5432
db_user=admin
db_pass=admin